OnlineShop_DjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('home_page.urls')),

    # about
    path('about/', include('about.urls')),

    # favourites
    path('favourites/', include('favourites.urls')),

    path('compare/', include('prod_comparison.urls')),

    # authentication
    path('', include('users.urls')),

    # shopping_cart
    path('cart/', include('shopping_cart.urls')),

    # main_page
    path('products/', include('main_page.urls'))
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

about/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.about, name='about')
]

favourites/urls.py
from django.urls import path
from . import views

app_name = 'favourites'

urlpatterns = [

    path('remove_favourite/<int:product_id>/', views.remove_favourite_status, name='remove_item'),

    path('favourites/<int:product_id>/', views.add_favourite_status, name='add_item'),

    path('', views.get_favourite_products, name='all_products'),

]

shopping_cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [

    path('', views.cart_view, name='cart'),

    # adding to cart
    path('add_item/<int:product_id>/', views.add_item, name='add_item'),

    # remove item
    path('remove_item/<int:product_id>/', views.remove_item, name='remove_item'),

    # update_item
    path('update_item/', views.update_cart, name='update_cart'),
]

favourites/models.py
from django.db import models
from django.contrib.auth.models import User
from main_page.models import Product


class Favourite(models.Model):
    product = models.ForeignKey(Product, verbose_name='Продукт', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')

    class Meta:
        ordering = ('product',)
        verbose_name = 'Избранное'
        verbose_name_plural = 'Избранное'

    def __str__(self):
        return f'Избранный товар {self.product} пользователя {self.user}'

favourites/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from main_page.models import Product, Menu
from .models import Favourite


@login_required
def get_favourite_products(request):
    menu = Menu.objects.all()
    user = request.user

    cart_prods_counter = user.shoppingcart_set.all()
    favourite_prods_counter = user.favourite_set.all()
    compare_prods_counter = user.compare_set.all()

    favourites_item = request.user.favourite_set.all()
    favourites_item = [item.product for item in favourites_item]

    return render(request, 'favourites/favourites.html', {
        'favourites_item': favourites_item,
        'menu': menu,
        'cart_prods_counter': cart_prods_counter,
        'favourite_prods_counter': favourite_prods_counter,
        'compare_prods_counter': compare_prods_counter,
    })


@login_required
def add_favourite_status(request, product_id):
    user = request.user
    product = get_object_or_404(Product, id=product_id)

    is_favourite = Favourite.objects.filter(product=product, user=request.user)

    if is_favourite:
        Favourite.objects.filter(user=user, product=product).delete()
    else:
        Favourite.objects.create(user=user, product=product)
    return redirect('main_page:index')


@login_required
def remove_favourite_status(request, product_id):
    fav_prods = Favourite.objects.filter(product_id=product_id).get(user_id=request.user.id)
    products = get_object_or_404(Favourite, id=fav_prods.id, user=request.user)
    if request.method == 'GET':
        products.delete()
    return redirect('favourites:all_products')

templates/favourites/favourites.html
{% extends 'main_page/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/favourites.css' %}">
{% endblock %}

{% block content %}
    <h2>Избранные товары</h2>
    <section class="favourites-content container content">
        <div class="favourites-tape">
            {% for item in favourites_item %}
                <div class="product-card">
                    <a href="{{ item.get_absolute_url }}">
                        <img src="{{ item.img.url }}" height="200" width="150" alt="Товар">
                    </a>

                    <div class="product-description">
                        <p>{{ item.name }}</p>
                        <p>{{ item.description }}</p>
                        <span><b>{{ item.price }} ₽</b></span>
                    </div>

                    <div class="interaction-item">
                        <a class="remove-prod" href="{% url 'favourites:remove_item' item.id %}">
                            <img src="{% static 'favourites/remove-icon.svg' %}" height="30" width="30"
                                 alt="Удалить избранное">
                        </a>

                        <a class="buy-prod" href="{% url 'cart:add_item' item.id %}">Купить</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </section>
{% endblock %}