OnlineShop_DjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('home_page.urls')),

    # about
    path('about/', include('about.urls')),

    # favourites
    path('favourites/', include('favourites.urls')),

    path('compare/', include('prod_comparison.urls')),

    # authentication
    path('', include('users.urls')),

    # shopping_cart
    path('cart/', include('shopping_cart.urls')),

    # main_page
    path('products/', include('main_page.urls'))
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

about/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.about, name='about')
]

favourites/urls.py
from django.urls import path
from . import views

app_name = 'favourites'

urlpatterns = [

    path('remove_favourite/<int:product_id>/', views.remove_favourite_status, name='remove_item'),

    path('favourites/<int:product_id>/', views.add_favourite_status, name='add_item'),

    path('', views.get_favourite_products, name='all_products'),

]

main_page/urls.py
from django.urls import path
from . import views

app_name = 'main_page'

urlpatterns = [
    # main_page
    path('', views.products_list, name='index'),

    # adding product
    path('add_product/', views.add_product, name='add_product'),

    # edit product page
    path('product/<int:prod_id>/<slug:slug>', views.product_detail, name='product_detail'),

    # delete prod
    path('product/<int:prod_id>/delete', views.delete_prod, name='delete'),

    # product category
    path('category/<slug:category_slug>/', views.products_list, name='product_list_by_category'),

    # product availability
    path('<str:product_availability>/', views.products_list, name='product_list_by_availability'),

    # view product page
    # path('product/<int:prod_id>/<slug:slug>', views.view_product, name='view_product'),
]

prod_comparison/urls.py
from django.urls import path
from . import views

app_name = 'compare'

urlpatterns = [

    path('remove_item/<int:product_id>/', views.remove_compare_status, name='remove_item'),

    path('add_item/<int:product_id>/', views.add_compare_status, name='add_item'),

    path('', views.get_compare_products, name='all_compare'),

]

shopping_cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [

    path('', views.cart_view, name='cart'),

    # adding to cart
    path('add_item/<int:product_id>/', views.add_item, name='add_item'),

    # remove item
    path('remove_item/<int:product_id>/', views.remove_item, name='remove_item'),

    # update_item
    path('update_item/', views.update_cart, name='update_cart'),
]

main_page/models.py
from django.db import models
from django.urls import reverse
from users.models import Profile
from django.contrib.auth.models import User
from shopping_cart.models import ShoppingCart


class Menu(models.Model):
    title = models.CharField(max_length=50)
    url = models.CharField(max_length=100)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Меню'
        verbose_name_plural = 'Меню'


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True, verbose_name='Категория')
    slug = models.SlugField(max_length=100, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def get_absolute_url(self):
        return reverse('main_page:product_list_by_category', args=[self.slug])

    def __str__(self):
        return self.name


class ProductAvailability(models.Model):
    availability_status = models.CharField(max_length=12, verbose_name='Статус товара', null=True)

    class Meta:
        verbose_name = 'Статус наличия'
        verbose_name_plural = 'Статусы наличия'

    def get_absolute_url(self):
        return reverse('main_page:product_list_by_availability', args=[self.availability_status])

    def __str__(self):
        return self.availability_status


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True,
                                 verbose_name='Категория')
    name = models.CharField(max_length=50, db_index=True, verbose_name='Наименование', null=True)
    slug = models.SlugField(max_length=100, db_index=True, null=True, verbose_name='Слаг')
    description = models.TextField(max_length=350, verbose_name='Описание', null=True)
    img = models.ImageField(upload_to='main_page/images', verbose_name='Изображение', null=True)
    width = models.CharField(max_length=10, verbose_name='Ширина (см)', null=True)
    height = models.CharField(max_length=10, verbose_name='Высота (см)', null=True)
    weight = models.CharField(max_length=10, verbose_name='Вес (кг)', null=True)
    price = models.FloatField(max_length=6, verbose_name='Цена (руб)', null=True)
    discount_price = models.CharField(max_length=10, null=True, verbose_name='Цена со скидкой')
    start_date = models.DateTimeField(null=True, blank=True, verbose_name='Дата старта распродажи')
    end_date = models.DateTimeField(null=True, blank=True, verbose_name='Дата окончания распродажи')
    availability_status = models.ForeignKey(ProductAvailability, on_delete=models.CASCADE, null=True, verbose_name='Наличие')
    vote_total = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now=True, null=True)

    cart_prods = models.ForeignKey(ShoppingCart, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name', '-vote_ratio', '-vote_total')
        index_together = ('id', 'slug',)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def get_absolute_url(self):
        return reverse('main_page:product_detail', args=[self.id, self.slug])

    def reviewers(self):
        queryset = self.review_set.all().values_list('owner_id', flat=True)
        return queryset

    def get_vote_count(self):
        reviews = self.review_set.all()
        up_votes = reviews.filter(value='За').count()
        total_votes = reviews.count()
        ratio = int((up_votes / total_votes) * 100)
        self.vote_total = total_votes
        self.vote_ratio = ratio
        self.save()


class Review(models.Model):
    VOTE_TYPE = (
        ('За', 'Голос за'),
        ('Против', 'Голос против')
    )

    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name='Автор')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Отзыв на')
    body = models.TextField(null=True, blank=True, verbose_name='Комментарий')
    value = models.CharField(max_length=200, choices=VOTE_TYPE, verbose_name='Голос', null=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создан')

    def __str__(self):
        return f'Пользователь {self.owner} оставил отзыв на {self.product}'

    class Meta:
        unique_together = [['owner', 'product'], ]
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

main_page/forms.py
from django.forms import ModelForm
from .models import Product, Review
from django import forms


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['body', 'value']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs.update({'class': 'input'})


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ['category', 'name', 'slug', 'description', 'img', 'width', 'height', 'weight', 'price',
                  'discount_price', 'start_date', 'end_date', 'availability_status']
        widgets = {
            'start_date': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'end_date': forms.DateTimeInput(attrs={'type': 'datetime-local'})
        }

main_page/views.py
from django.db import IntegrityError
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ProductForm, ReviewForm
from .models import *
from django.utils import timezone
from .utils import search_products
from favourites.models import Favourite
from prod_comparison.models import Compare


@login_required(login_url='login')
def products_list(request, category_slug=None, product_availability=None):
    curr_time = timezone.now()

    products, search_query = search_products(request)

    user = request.user

    favourite_prods = user.favourite_set.filter(user=user).values_list('product__id', flat=True)

    # compare_prods = user.compare_set.filter(user=user).values_list('product__id', flat=True)
    compare_prods = user.compare_set.filter(user=user).values_list('product_id', flat=True)
    print(compare_prods)

    menu = Menu.objects.all()
    categories = Category.objects.all()
    availabilities = ProductAvailability.objects.all()

    cart_prods_counter = user.shoppingcart_set.all()
    favourite_prods_counter = user.favourite_set.all()
    compare_prods_counter = user.compare_set.all()

    category, availability = None, None
    # функционал сортировки
    sort_by = request.GET.get('sort_by')

    if sort_by:
        products = Product.objects.order_by(sort_by).all()

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    if product_availability:
        availability = get_object_or_404(ProductAvailability, availability_status=product_availability)
        products = products.filter(availability_status=availability)

    context = {'menu': menu,
               'search_query': search_query,
               'category': category,
               'categories': categories,
               'availability': availability,
               'availabilities': availabilities,
               'products': products,
               'favourite_prods': favourite_prods,
               'compare_prods': compare_prods,
               'cart_prods_counter': cart_prods_counter,
               'favourite_prods_counter': favourite_prods_counter,
               'compare_prods_counter': compare_prods_counter,
               'curr_time': curr_time}
    return render(request, 'main_page/index.html', context)


@login_required
def add_product(request):
    menu = Menu.objects.all()

    cart_prods_counter = request.user.shoppingcart_set.all()
    favourite_prods_counter = request.user.favourite_set.all()
    compare_prods_counter = request.user.compare_set.all()

    if request.method == 'GET':
        return render(request, 'main_page/add_product.html', {'form': ProductForm(), 'menu': menu,
                                                              'cart_prods_counter': cart_prods_counter,
                                                              'favourite_prods_counter': favourite_prods_counter,
                                                              'compare_prods_counter': compare_prods_counter, })
    else:
        try:
            form = ProductForm(request.POST, request.FILES)
            new_product = form.save(commit=False)
            new_product.user = request.user
            new_product.save()
            return redirect('main_page:index')
        except ValueError:

            context = {
                'form': ProductForm(),
                'error': 'Переданы неверные данные', 'menu': menu,
                'cart_prods_counter': cart_prods_counter,
                'favourite_prods_counter': favourite_prods_counter,
                'compare_prods_counter': compare_prods_counter
            }
            return render(request, 'main_page/add_product.html', context)


@login_required
def product_detail(request, prod_id, slug):
    menu = Menu.objects.all()
    product = Product.objects.get(id=prod_id, slug=slug)

    cart_prods_counter = request.user.shoppingcart_set.all()
    favourite_prods_counter = request.user.favourite_set.all()
    compare_prods_counter = request.user.compare_set.all()

    if request.user.is_staff or request.user.is_superuser:
        if request.method == 'GET':
            form_prod = ProductForm(instance=product)

            context = {
                'menu': menu,
                'product': product,
                'form_prod': form_prod,
                'cart_prods_counter': cart_prods_counter,
                'favourite_prods_counter': favourite_prods_counter,
                'compare_prods_counter': compare_prods_counter
            }
            return render(request, 'main_page/edit_prod.html', context)
        else:
            try:
                form_prod = ProductForm(request.POST, instance=product)
                form_prod.save()

                return redirect('main_page:index')
            except ValueError:

                context = {
                    'product': product,
                    'menu': menu,
                    'cart_prods_counter': cart_prods_counter,
                    'favourite_prods_counter': favourite_prods_counter,
                    'compare_prods_counter': compare_prods_counter
                }
                return render(request, 'main_page/edit_prod.html', context)
    else:
        if request.method == 'GET':
            form_review = ReviewForm(request.GET)
            user_reviews = product.review_set.all()
            user_prof_data = request.user.profile

            context = {
                'product': product,
                'form_review': form_review,
                'menu': menu,
                'user_reviews': user_reviews,
                'user_prof_data': user_prof_data,
                'cart_prods_counter': cart_prods_counter,
                'favourite_prods_counter': favourite_prods_counter,
                'compare_prods_counter': compare_prods_counter
            }
            return render(request, 'main_page/view_prod.html', context)
        else:
            form_review = ReviewForm(request.POST)

            # try:
            review = form_review.save(commit=False)
            review.product = product
            review.owner = request.user.profile
            review.save()
            product.get_vote_count()
            messages.success(request, 'Ваш отзыв успешно сохранен')

            return redirect('main_page:product_detail', prod_id=product.id, slug=product.slug)
            # except IntegrityError:
    # return render(request, 'main_page/view_prod.html',
    #                           {'product': product,
    #                            'form_review': form_review,
    #                            'error': 'Неверные данные!'})


@login_required
def delete_prod(request, prod_id):
    product = get_object_or_404(Product, id=prod_id)
    if request.method == 'POST':
        product.delete()
        return redirect('main_page:index')

templates/main_page/add_product.html
{% extends 'main_page/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/add_prod.css' %}">
{% endblock %}

{% block content %}
    <h1>Добавление продукта</h1>

    <section>
        <div class="content container">
            <div class="add-product">
                <form method="post" class="add-form" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="button">
                        <button class="add-btn">Добавить</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

templates/main_page/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/Gilroy-Medium.woff' %}">
    <title>{% block title %}{% endblock %}</title>
    {% block css %} {% endblock %}
</head>
<body>
    <header class="page-header">
        <div class="page-header__wrapper container">

            <nav class="site-nav page-header__site-nav">
                <div class="page-header__logo">
                    <a href="{% url 'home_page' %}">
                        <img src="{% static 'main_page/funiro-logo.svg' %}" alt="Логотип">
                    </a>
                </div>

                <ul class="site-nav__list">
                    {% for item in menu %}
                        <li class="site-nav__item"><a href="{{ item.url }}">{{ item.title }}</a></li>
                    {% endfor %}
                </ul>
            </nav>

            <div class="site-nav__search-block">
                <form action="{% url 'main_page:index' %}" method="get">
                    <div class="form_field">
                        <input class="search-bar" id="formInput#search" type="text" name="search_query"
                               value="{{ search_query }}" placeholder="Поиск по продуктам"/>
                    </div>

                    <input type="submit" hidden="hidden" value="Search"/>
                </form>

            </div>

            <div class="user-nav__user-block">
                {% if user.is_authenticated %}

                    <div class="user-nav__shop_block">
                        <span class="cart-counter">{{ cart_prods_counter.count }}</span>
                        <span class="favourite-counter">{{ favourite_prods_counter.count }}</span>
                        <span class="compare-counter">{{ compare_prods_counter.count }}</span>

                        <a href="{% url 'cart:cart' %}"><img src="{% static 'main_page/shop_cart.svg' %}"
                                                             height="32" width="33" alt="Корзина товаров">
                        </a>

                        <a href="{% url 'favourites:all_products' %}"><img src="{% static 'main_page/favourites-icon.svg' %}"
                                                                           width="32" height="33" alt="Избранное">
                        </a>

                        <a href="{% url 'compare:all_compare' %}"><img src="{% static 'main_page/compare.svg' %}"
                                                                       width="32" height="33" alt="Избранное">
                        </a>
                    </div>

                    <div class="user-nav__profile">
                        <a class="user-nav__logo" id="user-icon" href="{% url 'main_page:index' %}">
                            <img src="{% static 'main_page/user_logo.svg' %}"
                                 width="32" height="33" alt="Пользователь">
                        </a>

                        <div class="dropdown-menu">
                            <ul class="controls-elem">
                                <li class="user-section">
                                    <a class="username" href="{% url 'profile' %}">{{ user }}</a>

                                    {% if user.is_superuser and user.is_staff %}
                                        <a class="product-controls" href="{% url 'main_page:add_product' %}">Добавить продукт</a>
                                    {% endif %}
                                </li>
                            </ul>

                            <ul class="user-dropdown-auth">
                                <li><a href="{% url 'login' %}">Сменить пользователя</a></li>
                                <li>
                                    <div class="logout-form">
                                        <form action="{% url 'logout' %}" method="post">
                                            {% csrf_token %}
                                            <button class="logout-btn">Выйти</button>
                                        </form>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                {% else %}

                    <ul class="user-nav__user-auth">
                        <li><a href="{% url 'signup' %}">Зарегистрироваться</a></li>
                        <li><a href="{% url 'login' %}">Войти</a></li>
                    </ul>
                {% endif %}
            </div>
        </div>
    </header>

{% block content %}{% endblock %}

{#        {% include 'main_page/footer.html' %}#}
</body>
</html>

templates/main_page/edit_prod.html
{% extends 'main_page/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/edit-prod.css' %}">
{% endblock %}

{% block content %}
    <h2>Управление товаром: <b>{{ product.name }}</b></h2>

    <section>
        <div class="content container">
            <div class="edit-product">
                <form method="post" class="edit-form" enctype="multipart/form-data">
                    {% csrf_token %}

                    {{ form_prod.as_p }}

                    <div class="button">
                        <button class="save-btn btn">Сохранить</button>
                    </div>
                </form>

                <div class="control-buttons">


                    <form action="{% url 'main_page:delete' product.id %}" method="post" class="edit-form">
                        {% csrf_token %}

                        <div class="button">
                            <button class="del-btn btn">Удалить</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/main_page/footer.html
{% load static %}

<footer class="basement-content">
    <div class="footer container">
        <div class="info-line">
            <div class="rights">
                <p>Designed and developed by Pavel Lukyanov</p>
                <p>Copyright © 2023</p>
            </div>

            <div class="info-line__menu">
                <a class="top-line__menu-item" href="https://t.me/Lukianov08">Связь с разработчиком</a>
            </div>
        </div>
    </div>
</footer>

templates/main_page/index.html
{% extends 'main_page/base.html' %}
{% load static %}
{% load tz %}
{% load i18n %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block title %}
    {% if category %} {{ category.name }} {% else %} Products {% endif %}
{% endblock %}

{% block content %}
    <section class="main-content container">
        <aside class="categories-block">
            <h2>Категории</h2>

            <ul class="categories-list">
                <a {% if not category or availability %} class="all-category-selected" {% endif %} href="{% url 'main_page:index' %}">
                    <li>Все</li>
                </a>

                {% for cat in categories %}
                    <a {% if category.slug == cat.slug %} {% endif %} class="cat-selected"
                                                                      href="{{ cat.get_absolute_url }}">
                        <li>{{ cat.name }}</li>
                    </a>
                {% endfor %}
            </ul>

            <ul class="products-availability">
                {% for avail in availabilities %}
                    <a {% if availability.availability_status == avail.availability_status %} {% endif %} href="{{ avail.get_absolute_url }}">
                        <li>{{ avail.availability_status }}</li>
                    </a>
                {% endfor %}
            </ul>
        </aside>

        <div class="catalog">
            <div class="sorting-product-section">
                <h3>Сортировка:</h3>
                <ul class="sorting-criteria">
                    <li><a class="sort-by" href="?sort_by=name">Название</a></li>
                    <li><a class="sort-by" href="?sort_by=price">Цена</a></li>
                </ul>
            </div>

            <div class="products-tape">
                {% for product in products %}
                    <div class="product-card">
                        <img src="{{ product.img.url }}" height="301" width="280" alt="Товар">

                        <div class="product-description">
                            <div class="product-info">
                                <a class="product-link" href="{{ product.get_absolute_url }}">
                                    <h3>{{ product.name }}</h3>
                                </a>
                                <p>{{ product.description }}</p>
                                {% if product.discount_price and product.start_date <= curr_time and curr_time <= product.end_date %}
                                    <div class="current_and_disc_price">
                                        <strike class="current-price">
                                            {% language 'ru' %}{{ product.price|floatformat:'2' }} ₽ {% endlanguage %}</strike>
                                        <span class="disc-price">{% language 'ru' %}{{ product.discount_price|floatformat:'2' }}
                                            ₽ {% endlanguage %}</span>
                                    </div>
                                {% else %}
                                    <span class="current-price">{% language 'ru' %}{{ product.price|floatformat:'2' }} ₽ {% endlanguage %}</span>
                                {% endif %}
                            </div>

                            {% if request.user.is_authenticated %}
                                <div class="interaction-item">
                                    {% if product.id in favourite_prods %}
                                        <a class="prod-is-fav" href="{% url 'favourites:add_item' product.id %}">
                                            <img src="{% static 'main_page/favourites-icon.svg' %}" alt="Избранное">
                                        </a>
                                    {% else %}
                                        <a class="prod-not-fav" href="{% url 'favourites:add_item' product.id %}">
                                            <img src="{% static 'main_page/favourites-icon.svg' %}" alt="Избранное">
                                        </a>
                                    {% endif %}

                                    {% if product.id in compare_prods %}
                                        <a class="prod-is-comp" href="{% url 'compare:add_item' product.id %}">
                                            <img src="{% static 'main_page/compare.svg' %}" alt="Избранное">
                                        </a>
                                    {% else %}
                                        <a class="prod-not-comp" href="{% url 'compare:add_item' product.id %}">
                                            <img src="{% static 'main_page/compare.svg' %}" alt="Избранное">
                                        </a>
                                    {% endif %}
                                </div>
                            {% endif %}
                        </div>

                        <div class="add_cart">
                            <a href="{% url 'cart:add_item' product.id %}">Добавить в корзину</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

templates/main_page/view_prod.html
{% extends 'main_page/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/view_prod.css' %}">
{% endblock %}

{% block content %}
    <h1>Просмотр товара: <b>{{ product.name }}</b></h1>

    <section class="content">
        <div class="view-product">
            {#            <div class="prod-img">#}
            <img src="{{ product.img.url }}" alt="">
            {#            </div>#}

            <table class="specific-product-table">
                <thead>
                <tr class="row-titles">
                    <th class="product-name">Наименование</th>
                    <th class="product-price">Цена (руб)</th>
                    <th class="product-width">Ширина (см)</th>
                    <th class="product-height">Высота (см)</th>
                    <th class="product-weight">Вес (кг)</th>
                    <th class="product-remove"></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td><p>{{ product.name }}</p></td>
                    <td><p>{{ product.price }}</p></td>
                    <td><p>{{ product.width }}</p></td>
                    <td><p>{{ product.height }}</p></td>
                    <td><p>{{ product.weight }}</p></td>
                </tr>
                </tbody>
            </table>
        </div>
    </section>

    <section class="feedback-content">
        <h2 class="container">Отзывы</h2>

        <div class="feedback_info container">
            <h3 class="feedback-rating">
                {{ product.vote_ratio }}% Положительных отзывов
                ({{ product.vote_total }} Vote{{ product.vote_total | pluralize:'s' }})
            </h3>

            <div class="create-feedback">
                {% if request.user.profile.id in product.reviewers %}
                    <p>Вы уже оставили свой отзыв на этот продукт</p>
                {% elif request.user.is_authenticated %}
                    <form class="form" action="{% url 'main_page:product_detail' product.id product.slug %}" method="POST">
                        {% csrf_token %}

                        {% for field in form_review %}
                            <div class="form_field">
                                <h3>{{ field.label }}</h3>
                                <p>{{ field }}</p>
                            </div>
                        {% endfor %}

                        <div class="leave-button">
                            <button class="leave-review-btn" type="submit">Оставить отзыв</button>
                        </div>
                    </form>
                {% else %}
                    <a href="{% url 'login' %}"></a>
                {% endif %}
            </div>
        </div>


        <div class="feedback-wrapper container">
            <div class="feedbacks-tape">
                {% for review in user_reviews %}
                    {% if review.body %}
                        <div class="feedback__item">
                            <div class="avatar-block">
                                <img src="{{ user_prof_data.img.url }}" height="50" width="50" alt="Фото профиля">
                            </div>

                            <div class="feedback-description">
                                <p>Пользователь: <b>{{ review.owner }}</b></p>

                                <p>Отзыв: <b>{{ review.body | linebreaksbr }}</b></p>

                                <p>Голос: <b>{{ review.value }}</b></p>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}