OnlineShop_DjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('home_page.urls')),

    # about
    path('about/', include('about.urls')),

    # favourites
    path('favourites/', include('favourites.urls')),

    path('compare/', include('prod_comparison.urls')),

    # authentication
    path('', include('users.urls')),

    # shopping_cart
    path('cart/', include('shopping_cart.urls')),

    # main_page
    path('products/', include('main_page.urls'))
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

about/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.about, name='about')
]

prod_comparison/urls.py
from django.urls import path
from . import views

app_name = 'compare'

urlpatterns = [

    path('remove_item/<int:product_id>/', views.remove_compare_status, name='remove_item'),

    path('add_item/<int:product_id>/', views.add_compare_status, name='add_item'),

    path('', views.get_compare_products, name='all_compare'),

]

shopping_cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [

    path('', views.cart_view, name='cart'),

    # adding to cart
    path('add_item/<int:product_id>/', views.add_item, name='add_item'),

    # remove item
    path('remove_item/<int:product_id>/', views.remove_item, name='remove_item'),

    # update_item
    path('update_item/', views.update_cart, name='update_cart'),
]

templates/prod_compare/compare_prod.html
{% extends 'main_page/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/compare.css' %}">
{% endblock %}

{% block content %}
    <h1 class="compare-app__title">Сравнение товаров</h1>

    <section class="container">
        <table class="compare-product-table">
            <thead>
                <tr class="row-titles">
                    <th class="product-thumbnail">&nbsp;</th>
                    <th class="product-name">Наименование</th>
                    <th class="product-price">Цена (руб)</th>
                    <th class="product-width">Ширина (см)</th>
                    <th class="product-height">Высота (см)</th>
                    <th class="product-weight">Вес (кг)</th>
                    <th class="product-remove"></th>
                </tr>
            </thead>
            <tbody>
                {% if compare_items %}
                    {% for spec in compare_items %}
                        <tr class="table-row">
                            <td><img src="{{ spec.img.url }}" height="150" width="150" alt="Товар"></td>
                            <td><p>{{ spec.product }}</p></td>
                            <td><p>{{ spec.price }}</p></td>
                            <td><p>{{ spec.width }}</p></td>
                            <td><p>{{ spec.height }}</p></td>
                            <td><p>{{ spec.weight }}</p></td>
                            <td class="product-action-section">
                                <div class="product-action">
                                    <a class="remove-prod" href="{% url 'compare:remove_item' spec.id %}">
                                        <img src="{% static 'shopping_cart/remove-icon.svg' %}" width="25px" height="25px"
                                             alt="Удалить товар">
                                    </a>

                                    <a class="buy-prod" href="{% url 'cart:add_item' spec.id %}">Купить</a>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                {% endif %}
            </tbody>
        </table>
    </section>
{% endblock %}