OnlineShop_DjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('home_page.urls')),

    # about
    path('about/', include('about.urls')),

    # favourites
    path('favourites/', include('favourites.urls')),

    path('compare/', include('prod_comparison.urls')),

    # authentication
    path('', include('users.urls')),

    # shopping_cart
    path('cart/', include('shopping_cart.urls')),

    # main_page
    path('products/', include('main_page.urls'))
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

about/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.about, name='about')
]

main_page/urls.py
from django.urls import path
from . import views

app_name = 'main_page'

urlpatterns = [
    # main_page
    path('', views.products_list, name='index'),

    # adding product
    path('add_product/', views.add_product, name='add_product'),

    # edit product page
    path('product/<int:prod_id>/<slug:slug>', views.product_detail, name='product_detail'),

    # delete prod
    path('product/<int:prod_id>/delete', views.delete_prod, name='delete'),

    # product category
    path('category/<slug:category_slug>/', views.products_list, name='product_list_by_category'),

    # product availability
    path('<str:product_availability>/', views.products_list, name='product_list_by_availability'),

    # view product page
    # path('product/<int:prod_id>/<slug:slug>', views.view_product, name='view_product'),
]

shopping_cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [

    path('', views.cart_view, name='cart'),

    # adding to cart
    path('add_item/<int:product_id>/', views.add_item, name='add_item'),

    # remove item
    path('remove_item/<int:product_id>/', views.remove_item, name='remove_item'),

    # update_item
    path('update_item/', views.update_cart, name='update_cart'),
]

shopping_cart/models.py
from django.db import models
from django.contrib.auth.models import User


class ShoppingCart(models.Model):
    name = models.CharField(max_length=50, verbose_name='Наименование')
    price = models.FloatField(max_length=20, verbose_name='Цена')
    img = models.ImageField(upload_to='main_page/images', null=True, verbose_name='Изображение')
    quantity = models.PositiveIntegerField(default=1, verbose_name='Количество')
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, verbose_name='Пользователь')

    class Meta:
        ordering = ('name',)
        verbose_name = 'Корзины'
        verbose_name_plural = 'Корзина'

    def __str__(self):
        return self.name

shopping_cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from main_page.models import Product, Menu
from .models import ShoppingCart
from django.db.models import Sum, ExpressionWrapper, F, DecimalField


@login_required
def cart_view(request):
    menu = Menu.objects.all()
    cart_items = ShoppingCart.objects.filter(user=request.user)
    cart_prods_counter = request.user.shoppingcart_set.all()
    favourite_prods_counter = request.user.favourite_set.all()
    compare_prods_counter = request.user.compare_set.all()
    total_price = cart_items.aggregate(
        total_price=Sum(ExpressionWrapper(F('price') * F('quantity'),
                                          output_field=DecimalField())))
    return render(request, 'shopping_cart/shopping_cart.html',
                  {'menu': menu,
                   'cart_items': cart_items,
                   'cart_prods_counter': cart_prods_counter,
                   'favourite_prods_counter': favourite_prods_counter,
                   'compare_prods_counter': compare_prods_counter,
                   'total_price': total_price['total_price']})


@login_required
def add_item(request, product_id):
    name = get_object_or_404(Product, id=product_id)
    cart_item, added = ShoppingCart.objects.get_or_create(name=name,
                                                          price=name.price,
                                                          img=name.img,
                                                          user=request.user)
    if not added:
        cart_item.quantity += 1
        cart_item.save()
    return redirect('main_page:index')


@login_required
def update_cart(request):
    if request.method == "POST":
        item_id = request.POST['item_id']
        new_quantity = int(request.POST['quantity'])
        cart_item = ShoppingCart.objects.get(id=item_id)
        cart_item.quantity = new_quantity
        cart_item.save()
        return redirect('cart:cart')


@login_required
def remove_item(request, product_id):
    product = get_object_or_404(ShoppingCart, id=product_id, user=request.user)
    if request.method == 'GET':
        product.delete()
    return redirect('cart:cart')

templates/shopping_cart/shopping_cart.html
{% extends 'main_page/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/cart.css' %}">
{% endblock %}

{% block content %}
    <h1>Корзина товаров</h1>

    <section class="cart-content container">
        {% if cart_items %}
            <table class="products-cart">
                <thead>
                    <tr class="row-titles">
                        <th class="product-thumbnail">&nbsp;</th>
                        <th class="product-name">Продукт</th>
                        <th class="product-price">Цена (руб)</th>
                        <th class="product-quantity">Количество (шт)</th>
                        <th class="product-remove"></th>
                    </tr>
                </thead>
                <tbody>
                    {% if cart_items %}
                        {% for item in cart_items %}
                        <tr class="row-titles">
                            <td class="product-thumbnail">
                                <a href="#">
                                    <img src="{{ item.img.url }}" alt="{{ item.title }}" height="150" width="150"
                                          class="item-img">
                                </a>
                            </td>
                            <td class="product-name"><a href="#">{{ item.name }}</a></td>
                            <td class="product-price"><a href="#">{{ item.price }}</a></td>
                            <td class="product-quantity">
                                <a href="#">
                                   <form method="POST" action="{% url 'cart:update_cart' %}" class="update-quantity-form">
                                       {% csrf_token %}
                                       <input type="hidden" name="item_id" value="{{ item.id }}">
                                       <input type="number" name="quantity" value="{{ item.quantity }}" min="1" max="100">
                                       <button type="submit">Обновить</button>
                                   </form>
                                </a>
                            </td>
                            <td class="product-remove">
                                <a href="{% url 'cart:remove_item' item.id %}">
                                    <img src="{% static 'shopping_cart/remove-icon.svg' %}" width="25px" height="25px"
                                         alt="Удалить товар">
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    {% endif %}
                </tbody>
            </table>

            <div class="count-total-price">
                <h3>Итого: </h3>
                <p>{{ total_price }} ₽</p>
            </div>

            {% else %}
            <div class="cart-is-empty">
                <img src="{% static 'shopping_cart/empty-cart.svg' %}" height="100" width="100" alt="Корзина товаров">
                <p id="cart-empty">Корзина пуста</p>
                <p id="go-shop">Возвращайтесь к <a href="{% url 'main_page:index' %}">покупкам</a></p>
            </div>
        {% endif %}
    </section>
{% endblock %}